### ISSUE TITLE
use `dict.get`

### ISSUE THREAD

**Issue by sifte** [Okimii/Akeno#6]
Consider using `dict.get()` rather than indexing dictionaries because `dict.get()` would return `None` if the key was not in the dictionary whereas indexing the dictionary would raise a KeyError if the key was not in the dictionary.
```py
>>> dict = {}
>>> dict.get("1")
None
```

```py
>>> dict = {}
>>> dict["1"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '1'
```

**Comment by Okimii** [comment]
we will not add handling for it since if it returns None and youre trying to index it you will get a Nonetype error which why add this feature if we already have handling for keyerrors and not Nonetype to change the method to handle another error isnt really making something better
